title: SpecuCheck
description: SpecuCheck is a Windows utility for checking the state of the software mitigations against CVE-2017-5754 (Meltdown) and hardware mitigations against CVE-2017-5715 (Spectre) 
show_downloads: true
theme: jekyll-theme-hacker
