[package]
publish = false
name = "wfsexploit"
description = "wfshbr64.sys and wfshbr32.sys specially crafted payload allows local privilege escalation"
readme = "README.md"
version = "0.1.0"
authors = ["Kento Oki <hrn832@protonmail.com>", "Kenjiro Ichise"]
edition = "2021"
homepage = "https://github.com/kkent030315/CVE-2022-42046"
repository = "https://github.com/kkent030315/CVE-2022-42046"
license-file = "LICENSE"

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
ntapi = "0.4.0"
winapi = { version = "0.3", features = ["fileapi",
                                        "handleapi",
                                        "winioctl",
                                        "ioapiset"] }
num = "0.4.0"

[dev-dependencies]
speculate = "0.1.2"
